### PR TITLE
typo in debug help string

### PR DESCRIPTION
**Pull request by stites**

### CODE REVIEW

**Comment by NorfairKing** [comment]
Well, this is a great way to show me that the CI is broken for nightly stackage builds. Will fix that and merge this!

**Comment by stites** [comment]
haha, excellent. Thanks for this project -- it's been a life saver.

**Comment by NorfairKing** [comment]
Thank you for the kind words! Feedback always welcome.

**Comment by stites** [comment]
I think #22 should fix travis, you might want to trigger a rebuild on this one

**Comment by NorfairKing** [comment]
@stites Fantastic! I triggered a rebuild but I think you may have to rebase.

**Comment by stites** [comment]
looks like something is wrong with this PR. closing in favor of #23

**Pull request closed without merging**
